services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
      - "./data:/data"  # Mount point for data uploads
    ulimits:
      nofile:
        soft: 8192
        hard: 65536

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"

  # New CLI service for handling uploads
  omerocli:
    image: "openmicroscopy/omero-cli:latest"
    networks:
      - omero
    volumes:
      - "./data:/data"  # Shared volume with omeroserver for uploads
    depends_on:
      - omeroserver
    # Keep container running
    tty: true
    stdin_open: true

networks:
  omero:
    external: true

volumes:
  database:
  omero: