apiVersion: v1
kind: ConfigMap
metadata:
  name: node-hostnames
  namespace: kube-system
data:
  hosts: |
    # Kubernetes Cluster Nodes
    # Replace <MASTER_IP> and <WORKER_IP> with your actual IP addresses
    <MASTER_IP> master-node
    <WORKER_IP> worker-01

---
apiVersion: v1
kind: Pod
metadata:
  name: hostname-updater
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: hostname-updater
    image: busybox:1.28
    command: ['sh', '-c', 'while true; do cat /config/hosts >> /etc/hosts; sleep 3600; done']
    volumeMounts:
    - name: hosts-config
      mountPath: /config
    - name: hosts-file
      mountPath: /etc/hosts
  volumes:
  - name: hosts-config
    configMap:
      name: node-hostnames
  - name: hosts-file
    hostPath:
      path: /etc/hosts